32 modeler developer preview
camunda/camunda-platform pull request #36
Opened 2022-10-06 14:17 UTC by pihme

closes #32

2022-10-06 14:43 UTC, pihme commented
> What is the tarball used for?

Will be removed during cleanup

2022-10-07 10:37 UTC, pihme commented
@jfriedenstab Please have a look, if there is still time before your holidays. There is still one open TODO - to replace the latest version with the actual release tag. Other than that it is complete.

I kept the ports now as is. Didn't want to meddle with it too much so short before the deadline.

2022-10-07 10:45 UTC, pihme commented
There is one known issue with this setup: https://github.com/camunda/web-modeler/issues/2609

2022-10-09 14:28 UTC, jfriedenstab requested changes
Nice! Just a couple of smaller remarks.

2022-10-09 14:28 UTC, jfriedenstab commented on docker-compose-web-modeler-beta.yaml
> +    # accordingly
Real SMTP servers probably require authentication:

```suggestion
    # If you want to use your own SMTP server, you can remove this container
    # and configure RESTAPI_MAIL_HOST, RESTAPI_MAIL_PORT, RESTAPI_MAIL_USER, RESTAPI_MAIL_PASSWORD, and RESTAPI_MAIL_ENABLE_TLS
    # accordingly
```

2022-10-09 14:28 UTC, jfriedenstab commented on docker-compose-web-modeler-beta.yaml
> +      RESTAPI_SERVER_URL: http://localhost:8081
`RESTAPI_SERVER_URL` has to use the exposed port of the webapp: `http://localhost:8070`
It is used, for example, to construct the URL for project invitations (which are opened in the browser).

2022-10-09 14:28 UTC, jfriedenstab commented on docker-compose-web-modeler-beta.yaml
> +    container_name: websockets
```suggestion
    container_name: modeler-websockets
```
(The other containers' names are all prefixed)

2022-10-09 14:35 UTC, jfriedenstab commented
One more thing that might be noteworthy in the `README` file:
When you want to deploy a diagram to the local Zeebe cluster you need to use the name of the Zeebe container as the host name instead of `localhost` (so the cluster endpoint would be `zeebe:26500`). This is different from the Desktop Modeler.

2022-10-10 08:48 UTC, pihme commented
@christian-konrad Please have a look at the README.md changes in particular

2022-10-10 11:21 UTC, jfriedenstab approved these changes
:tada:

2022-10-10 16:01 UTC, christian-konrad approved these changes
I like it! Well done

2022-10-10 16:11 UTC, merged